### ISSUE TITLE
bug: fail to read the files

### ISSUE THREAD

**Issue by elaragao** [LarissaStein/DataAnalysis#1]
@LarissaStein The first function presents problems identifing possible values of the analysis.

**Comment by elaragao** [comment]
https://github.com/LarissaStein/DataAnalysis/blob/80d92451e7e176748844086cbaba125f86e09fa4/XRD.py#L10C1-L11C1

The problem is in this line. When you use "isnumeric()" you only analyse the strings that could be read usually as "int". Anything with "." or anything like that, is consider a string that can not be applied this function.

**Comment by LarissaStein** [comment]
Thank you for point this out. Solved.
